### PR TITLE
Test: add snapshot for HeaderDropdown component

### PR DESCRIPTION
**Pull request by Vuologist**

### CODE REVIEW

**Comment by choum** [comment]
image

Every thing looks good, but I'm not a huge fan of how the html is formatted here when theres only the class name attribute in there

**Comment by Vuologist** [comment]
> image
> 
> Every thing looks good, but I'm not a huge fan of how the html is formatted here when theres only the class name attribute in there

what would u prefer?

**Comment by choum** [comment]
ex

> > image
> > Every thing looks good, but I'm not a huge fan of how the html is formatted here when theres only the class name attribute in there
> 
> what would u prefer?

ex: <li className="c1"> instead of 
<li
   className="c1"
>

**Comment by Vuologist** [comment]
@choum pls review once you merge your branch in

**Pull request merged**
