### PR TITLE
Feat: add aws sign up call to sign in page

### LINKED ISSUE #76: Frontend - implement sign up on login page (2)
DoD: be able to sign up with new credentials and sign in

### PR DESCRIPTION
**Pull request by Vuologist**
closes #76 

**Test Instructions:**

**Test 1**
- open chrome console
- enter a random email to the email field
- enter a password such as Password1@ to password field
- enter a same password to confirm password field

if everything worked then you should see nothing.

**Test 2**
- open chrome console
- enter a random email to the email field
- enter a password such as password1@ to password field
- enter a same password to confirm password field

if everything worked then you should see an alert that password does not meet password requirement.

### CODE REVIEW

**Review by choum — CHANGES_REQUESTED** [review]
enter button submits the form

**Review by choum — CHANGES_REQUESTED** [review]
https://media.discordapp.net/attachments/496696958795382796/757829761467809802/unknown.png

resolve error or create new issue to cover this error

**Comment by Vuologist** [comment]
> enter button submits the form

fixed

**Comment by Vuologist** [comment]
> https://media.discordapp.net/attachments/496696958795382796/757829761467809802/unknown.png
> 
> resolve error or create new issue to cover this error

will be solved in #89

**Review by choum — APPROVED** [review]
looks good to me

**Pull request merged**
